const mongoose = require('mongoose');

const settingsSchema = new mongoose.Schema({
  restaurantName: { type: String, default: 'HUMTUM Billing System' },
  address:        { type: String, default: '' },
  gstin:          { type: String, default: '' },
  phone:          { type: String, default: '' },
  sgstRate:       { type: Number, default: 0 },
  cgstRate:       { type: Number, default: 0 },
  serviceTaxEnabled: { type: Boolean, default: false },
  serviceTaxRate: { type: Number, default: 0 },
  currency:       { type: String, default: '₹' },
  thankYouMsg:    { type: String, default: '' },
  darkMode:       { type: Boolean, default: true },
  directPrinting: { type: Boolean, default: false },
  qzTrayEnabled:  { type: Boolean, default: false },
  printAgentEnabled: { type: Boolean, default: false },
  printAgentPort: { type: Number, default: 5001 },
  printAgentToken: { type: String, default: '' },
  kitchenPrinterName: { type: String, default: '' },
  barPrinterName: { type: String, default: '' },
  billingPrinterName: { type: String, default: '' },
  detectedPrinters: { type: [String], default: [] },
  upiId:          { type: String, default: '' },
  includeUpiAmount: { type: Boolean, default: true },
  adminEmail:     { type: String, default: '' },
  senderEmail:    { type: String, default: '' },
  senderPassword: { type: String, default: '' },
  inventoryCategories: { type: [String], default: ['Spirits','Beer','Wine','Food','Mixers'] },
  menuCategories:      { type: [String], default: ['Spirits','Beer','Wine','Food','Mixers'] },
  googleReviewLink:    { type: String, default: 'https://g.page/r/CQnCGIPFlqaOEBM/review' },
  instagramLink:       { type: String, default: 'https://www.instagram.com/humtum.thebar/' },
  facebookLink:        { type: String, default: 'https://www.facebook.com/humtum.thebar/' },
  whatsappEnabled:     { type: Boolean, default: true },
  whatsappTemplate:    { type: String, default: 'Hello {customerName}!\n\nThank you for visiting HumTum Bar & Club. We hope you had a wonderful time! 🍹✨\n\nCould you please take a moment to share your experience with us? It helps us grow!\nGoogle Review: {googleReviewLink}\n\nFollow us to stay updated with our events and offers:\nInstagram: {instagramLink}\nFacebook: {facebookLink}\n\nHope to see you again soon!\nTeam HumTum' },
  isDryDay:            { type: Boolean, default: false },
  maxDiscountLimit:    { type: Number, default: 30 },
}, { timestamps: true });

module.exports = mongoose.model('Settings', settingsSchema);
